enum KratosError {
  infoSelfServiceLoginRoot,
  infoSelfServiceLogin,
  infoSelfServiceLoginWith,
  infoSelfServiceLoginReAuth,
  infoSelfServiceLoginMFA,
  infoSelfServiceLoginVerify,
  infoSelfServiceLoginTOTPLabel,
  infoLoginLookupLabel,
  infoSelfServiceLoginWebAuthn,
  infoLoginTOTP,
  infoLoginLookup,
  infoSelfServiceLoginContinueWebAuthn,
  infoSelfServiceLoginWebAuthnPasswordless,
  infoSelfServiceLoginContinue,
  infoSelfServiceLogout,
  infoSelfServiceMFA,
  infoSelfServiceRegistrationRoot,
  infoSelfServiceRegistration,
  infoSelfServiceRegistrationWith,
  infoSelfServiceRegistrationContinue,
  infoSelfServiceRegistrationRegisterWebAuthn,
  infoSelfServiceSettings,
  infoSelfServiceSettingsUpdateSuccess,
  infoSelfServiceSettingsUpdateLinkOidc,
  infoSelfServiceSettingsUpdateUnlinkOidc,
  infoSelfServiceSettingsUpdateUnlinkTOTP,
  infoSelfServiceSettingsTOTPQRCode,
  infoSelfServiceSettingsTOTPSecret,
  infoSelfServiceSettingsRevealLookup,
  infoSelfServiceSettingsRegenerateLookup,
  infoSelfServiceSettingsLookupSecret,
  infoSelfServiceSettingsLookupSecretLabel,
  infoSelfServiceSettingsLookupConfirm,
  infoSelfServiceSettingsRegisterWebAuthn,
  infoSelfServiceSettingsRegisterWebAuthnDisplayName,
  infoSelfServiceSettingsLookupSecretUsed,
  infoSelfServiceSettingsLookupSecretList,
  infoSelfServiceSettingsDisableLookup,
  infoSelfServiceSettingsTOTPSecretLabel,
  infoSelfServiceSettingsRemoveWebAuthn,
  infoSelfServiceRecovery,
  infoSelfServiceRecoverySuccessful,
  infoSelfServiceRecoveryEmailSent,
  infoSelfServiceRecoveryEmailWithCodeSent,
  infoNodeLabel,
  infoNodeLabelInputPassword,
  infoNodeLabelGenerated,
  infoNodeLabelSave,
  infoNodeLabelID,
  infoNodeLabelSubmit,
  infoNodeLabelVerifyOTP,
  infoNodeLabelEmail,
  infoNodeLabelResendOTP,
  infoNodeLabelContinue,
  infoNodeLabelRecoveryCode,
  infoNodeLabelVerificationCode,
  infoSelfServiceVerification,
  infoSelfServiceVerificationEmailSent,
  infoSelfServiceVerificationSuccessful,
  infoSelfServiceVerificationEmailWithCodeSent,
  errorValidation,
  errorValidationGeneric,
  errorValidationRequired,
  errorValidationMinLength,
  errorValidationInvalidFormat,
  errorValidationPasswordPolicyViolation,
  errorValidationInvalidCredentials,
  errorValidationDuplicateCredentials,
  errorValidationTOTPVerifierWrong,
  errorValidationIdentifierMissing,
  errorValidationAddressNotVerified,
  errorValidationNoTOTPDevice,
  errorValidationLookupAlreadyUsed,
  errorValidationNoWebAuthnDevice,
  errorValidationNoLookup,
  errorValidationSuchNoWebAuthnUser,
  errorValidationLookupInvalid,
  errorValidationMaxLength,
  errorValidationMinimum,
  errorValidationExclusiveMinimum,
  errorValidationMaximum,
  errorValidationExclusiveMaximum,
  errorValidationMultipleOf,
  errorValidationMaxItems,
  errorValidationMinItems,
  errorValidationUniqueItems,
  errorValidationWrongType,
  errorValidationDuplicateCredentialsOnOIDCLink,
  errorValidationLogin,
  errorValidationLoginFlowExpired,
  errorValidationLoginNoStrategyFound,
  errorValidationRegistrationNoStrategyFound,
  errorValidationSettingsNoStrategyFound,
  errorValidationRecoveryNoStrategyFound,
  errorValidationVerificationNoStrategyFound,
  errorValidationPasswordTooSimilar,
  errorValidationPasswordLeaked,
  errorValidationRegistration,
  errorValidationRegistrationFlowExpired,
  errorValidationSettings,
  errorValidationSettingsFlowExpired,
  errorValidationRecovery,
  errorValidationRecoveryRetrySuccess,
  errorValidationRecoveryStateFailure,
  errorValidationRecoveryMissingRecoveryToken,
  errorValidationRecoveryTokenInvalidOrAlreadyUsed,
  errorValidationRecoveryFlowExpired,
  errorValidationRecoveryCodeInvalidOrAlreadyUsed,
  errorValidationVerification,
  errorValidationVerificationTokenInvalidOrAlreadyUsed,
  errorValidationVerificationRetrySuccess,
  errorValidationVerificationStateFailure,
  errorValidationVerificationMissingVerificationToken,
  errorValidationVerificationFlowExpired,
  errorValidationVerificationCodeInvalidOrAlreadyUsed,
  errorSystem,
  errorSystemGeneric;

  static KratosError forId(int id) {
    return switch (id) {
      // Login
      1010000 => KratosError.infoSelfServiceLoginRoot,
      1010001 => KratosError.infoSelfServiceLogin,
      1010002 => KratosError.infoSelfServiceLoginWith,
      1010003 => KratosError.infoSelfServiceLoginReAuth,
      1010004 => KratosError.infoSelfServiceLoginMFA,
      1010005 => KratosError.infoSelfServiceLoginVerify,
      1010006 => KratosError.infoSelfServiceLoginTOTPLabel,
      1010007 => KratosError.infoLoginLookupLabel,
      1010008 => KratosError.infoSelfServiceLoginWebAuthn,
      1010009 => KratosError.infoLoginTOTP,
      1010010 => KratosError.infoLoginLookup,
      1010011 => KratosError.infoSelfServiceLoginContinueWebAuthn,
      1010012 => KratosError.infoSelfServiceLoginWebAuthnPasswordless,
      1010013 => KratosError.infoSelfServiceLoginContinue,

      // Logout
      1020000 => KratosError.infoSelfServiceLogout,

      // MFA
      1030000 => KratosError.infoSelfServiceMFA,

      // Registration
      1040000 => KratosError.infoSelfServiceRegistrationRoot,
      1040001 => KratosError.infoSelfServiceRegistration,
      1040002 => KratosError.infoSelfServiceRegistrationWith,
      1040003 => KratosError.infoSelfServiceRegistrationContinue,
      1040004 => KratosError.infoSelfServiceRegistrationRegisterWebAuthn,

      // Settings
      1050000 => KratosError.infoSelfServiceSettings,
      1050001 => KratosError.infoSelfServiceSettingsUpdateSuccess,
      1050002 => KratosError.infoSelfServiceSettingsUpdateLinkOidc,
      1050003 => KratosError.infoSelfServiceSettingsUpdateUnlinkOidc,
      1050004 => KratosError.infoSelfServiceSettingsUpdateUnlinkTOTP,
      1050005 => KratosError.infoSelfServiceSettingsTOTPQRCode,
      1050006 => KratosError.infoSelfServiceSettingsTOTPSecret,
      1050007 => KratosError.infoSelfServiceSettingsRevealLookup,
      1050008 => KratosError.infoSelfServiceSettingsRegenerateLookup,
      1050009 => KratosError.infoSelfServiceSettingsLookupSecret,
      1050010 => KratosError.infoSelfServiceSettingsLookupSecretLabel,
      1050011 => KratosError.infoSelfServiceSettingsLookupConfirm,
      1050012 => KratosError.infoSelfServiceSettingsRegisterWebAuthn,
      1050013 => KratosError.infoSelfServiceSettingsRegisterWebAuthnDisplayName,
      1050014 => KratosError.infoSelfServiceSettingsLookupSecretUsed,
      1050015 => KratosError.infoSelfServiceSettingsLookupSecretList,
      1050016 => KratosError.infoSelfServiceSettingsDisableLookup,
      1050017 => KratosError.infoSelfServiceSettingsTOTPSecretLabel,
      1050018 => KratosError.infoSelfServiceSettingsRemoveWebAuthn,

      // Recovery
      1060000 => KratosError.infoSelfServiceRecovery,
      1060001 => KratosError.infoSelfServiceRecoverySuccessful,
      1060002 => KratosError.infoSelfServiceRecoveryEmailSent,
      1060003 => KratosError.infoSelfServiceRecoveryEmailWithCodeSent,

      // Node Label
      1070000 => KratosError.infoNodeLabel,
      1070001 => KratosError.infoNodeLabelInputPassword,
      1070002 => KratosError.infoNodeLabelGenerated,
      1070003 => KratosError.infoNodeLabelSave,
      1070004 => KratosError.infoNodeLabelID,
      1070005 => KratosError.infoNodeLabelSubmit,
      1070006 => KratosError.infoNodeLabelVerifyOTP,
      1070007 => KratosError.infoNodeLabelEmail,
      1070008 => KratosError.infoNodeLabelResendOTP,
      1070009 => KratosError.infoNodeLabelContinue,
      1070010 => KratosError.infoNodeLabelRecoveryCode,
      1070011 => KratosError.infoNodeLabelVerificationCode,

      // Verification
      1080000 => KratosError.infoSelfServiceVerification,
      1080001 => KratosError.infoSelfServiceVerificationEmailSent,
      1080002 => KratosError.infoSelfServiceVerificationSuccessful,
      1080003 => KratosError.infoSelfServiceVerificationEmailWithCodeSent,

      // Validation Error
      4000000 => KratosError.errorValidation,
      4000001 => KratosError.errorValidationGeneric,
      4000002 => KratosError.errorValidationRequired,
      4000003 => KratosError.errorValidationMinLength,
      4000004 => KratosError.errorValidationInvalidFormat,
      4000005 => KratosError.errorValidationPasswordPolicyViolation,
      4000006 => KratosError.errorValidationInvalidCredentials,
      4000007 => KratosError.errorValidationDuplicateCredentials,
      4000008 => KratosError.errorValidationTOTPVerifierWrong,
      4000009 => KratosError.errorValidationIdentifierMissing,
      4000010 => KratosError.errorValidationAddressNotVerified,
      4000011 => KratosError.errorValidationNoTOTPDevice,
      4000012 => KratosError.errorValidationLookupAlreadyUsed,
      4000013 => KratosError.errorValidationNoWebAuthnDevice,
      4000014 => KratosError.errorValidationNoLookup,
      4000015 => KratosError.errorValidationSuchNoWebAuthnUser,
      4000016 => KratosError.errorValidationLookupInvalid,
      4000017 => KratosError.errorValidationMaxLength,
      4000018 => KratosError.errorValidationMinimum,
      4000019 => KratosError.errorValidationExclusiveMinimum,
      4000020 => KratosError.errorValidationMaximum,
      4000021 => KratosError.errorValidationExclusiveMaximum,
      4000022 => KratosError.errorValidationMultipleOf,
      4000023 => KratosError.errorValidationMaxItems,
      4000024 => KratosError.errorValidationMinItems,
      4000025 => KratosError.errorValidationUniqueItems,
      4000026 => KratosError.errorValidationWrongType,
      4000027 => KratosError.errorValidationDuplicateCredentialsOnOIDCLink,
      4000031 => KratosError.errorValidationPasswordTooSimilar,
      4000034 => KratosError.errorValidationPasswordLeaked,

      // Login Validation Error
      4010000 => KratosError.errorValidationLogin,
      4010001 => KratosError.errorValidationLoginFlowExpired,
      4010002 => KratosError.errorValidationLoginNoStrategyFound,
      4010003 => KratosError.errorValidationRegistrationNoStrategyFound,
      4010004 => KratosError.errorValidationSettingsNoStrategyFound,
      4010005 => KratosError.errorValidationRecoveryNoStrategyFound,
      4010006 => KratosError.errorValidationVerificationNoStrategyFound,

      // Registration Validation Error
      4040000 => KratosError.errorValidationRegistration,
      4040001 => KratosError.errorValidationRegistrationFlowExpired,

      // Settings Validation Error
      4050000 => KratosError.errorValidationSettings,
      4050001 => KratosError.errorValidationSettingsFlowExpired,

      // Recovery Validation Error
      4060000 => KratosError.errorValidationRecovery,
      4060001 => KratosError.errorValidationRecoveryRetrySuccess,
      4060002 => KratosError.errorValidationRecoveryStateFailure,
      4060003 => KratosError.errorValidationRecoveryMissingRecoveryToken,
      4060004 => KratosError.errorValidationRecoveryTokenInvalidOrAlreadyUsed,
      4060005 => KratosError.errorValidationRecoveryFlowExpired,
      4060006 => KratosError.errorValidationRecoveryCodeInvalidOrAlreadyUsed,

      // Verification Validation Error
      4070000 => KratosError.errorValidationVerification,
      4070001 =>
        KratosError.errorValidationVerificationTokenInvalidOrAlreadyUsed,
      4070002 => KratosError.errorValidationVerificationRetrySuccess,
      4070003 => KratosError.errorValidationVerificationStateFailure,
      4070004 =>
        KratosError.errorValidationVerificationMissingVerificationToken,
      4070005 => KratosError.errorValidationVerificationFlowExpired,
      4070006 =>
        KratosError.errorValidationVerificationCodeInvalidOrAlreadyUsed,

      // System Error
      5000000 => KratosError.errorSystem,
      5000001 => KratosError.errorSystemGeneric,
      _ => KratosError.errorSystemGeneric
    };
  }
}
