enum KratosErrors {
  infoSelfServiceLoginRoot,
  infoSelfServiceLogin,
  infoSelfServiceLoginWith,
  infoSelfServiceLoginReAuth,
  infoSelfServiceLoginMFA,
  infoSelfServiceLoginVerify,
  infoSelfServiceLoginTOTPLabel,
  infoLoginLookupLabel,
  infoSelfServiceLoginWebAuthn,
  infoLoginTOTP,
  infoLoginLookup,
  infoSelfServiceLoginContinueWebAuthn,
  infoSelfServiceLoginWebAuthnPasswordless,
  infoSelfServiceLoginContinue,
  infoSelfServiceLogout,
  infoSelfServiceMFA,
  infoSelfServiceRegistrationRoot,
  infoSelfServiceRegistration,
  infoSelfServiceRegistrationWith,
  infoSelfServiceRegistrationContinue,
  infoSelfServiceRegistrationRegisterWebAuthn,
  infoSelfServiceSettings,
  infoSelfServiceSettingsUpdateSuccess,
  infoSelfServiceSettingsUpdateLinkOidc,
  infoSelfServiceSettingsUpdateUnlinkOidc,
  infoSelfServiceSettingsUpdateUnlinkTOTP,
  infoSelfServiceSettingsTOTPQRCode,
  infoSelfServiceSettingsTOTPSecret,
  infoSelfServiceSettingsRevealLookup,
  infoSelfServiceSettingsRegenerateLookup,
  infoSelfServiceSettingsLookupSecret,
  infoSelfServiceSettingsLookupSecretLabel,
  infoSelfServiceSettingsLookupConfirm,
  infoSelfServiceSettingsRegisterWebAuthn,
  infoSelfServiceSettingsRegisterWebAuthnDisplayName,
  infoSelfServiceSettingsLookupSecretUsed,
  infoSelfServiceSettingsLookupSecretList,
  infoSelfServiceSettingsDisableLookup,
  infoSelfServiceSettingsTOTPSecretLabel,
  infoSelfServiceSettingsRemoveWebAuthn,
  infoSelfServiceRecovery,
  infoSelfServiceRecoverySuccessful,
  infoSelfServiceRecoveryEmailSent,
  infoSelfServiceRecoveryEmailWithCodeSent,
  infoNodeLabel,
  infoNodeLabelInputPassword,
  infoNodeLabelGenerated,
  infoNodeLabelSave,
  infoNodeLabelID,
  infoNodeLabelSubmit,
  infoNodeLabelVerifyOTP,
  infoNodeLabelEmail,
  infoNodeLabelResendOTP,
  infoNodeLabelContinue,
  infoNodeLabelRecoveryCode,
  infoNodeLabelVerificationCode,
  infoSelfServiceVerification,
  infoSelfServiceVerificationEmailSent,
  infoSelfServiceVerificationSuccessful,
  infoSelfServiceVerificationEmailWithCodeSent,
  errorValidation,
  errorValidationGeneric,
  errorValidationRequired,
  errorValidationMinLength,
  errorValidationInvalidFormat,
  errorValidationPasswordPolicyViolation,
  errorValidationInvalidCredentials,
  errorValidationDuplicateCredentials,
  errorValidationTOTPVerifierWrong,
  errorValidationIdentifierMissing,
  errorValidationAddressNotVerified,
  errorValidationNoTOTPDevice,
  errorValidationLookupAlreadyUsed,
  errorValidationNoWebAuthnDevice,
  errorValidationNoLookup,
  errorValidationSuchNoWebAuthnUser,
  errorValidationLookupInvalid,
  errorValidationMaxLength,
  errorValidationMinimum,
  errorValidationExclusiveMinimum,
  errorValidationMaximum,
  errorValidationExclusiveMaximum,
  errorValidationMultipleOf,
  errorValidationMaxItems,
  errorValidationMinItems,
  errorValidationUniqueItems,
  errorValidationWrongType,
  errorValidationDuplicateCredentialsOnOIDCLink,
  errorValidationLogin,
  errorValidationLoginFlowExpired,
  errorValidationLoginNoStrategyFound,
  errorValidationRegistrationNoStrategyFound,
  errorValidationSettingsNoStrategyFound,
  errorValidationRecoveryNoStrategyFound,
  errorValidationVerificationNoStrategyFound,
  errorValidationRegistration,
  errorValidationRegistrationFlowExpired,
  errorValidationSettings,
  errorValidationSettingsFlowExpired,
  errorValidationRecovery,
  errorValidationRecoveryRetrySuccess,
  errorValidationRecoveryStateFailure,
  errorValidationRecoveryMissingRecoveryToken,
  errorValidationRecoveryTokenInvalidOrAlreadyUsed,
  errorValidationRecoveryFlowExpired,
  errorValidationRecoveryCodeInvalidOrAlreadyUsed,
  errorValidationVerification,
  errorValidationVerificationTokenInvalidOrAlreadyUsed,
  errorValidationVerificationRetrySuccess,
  errorValidationVerificationStateFailure,
  errorValidationVerificationMissingVerificationToken,
  errorValidationVerificationFlowExpired,
  errorValidationVerificationCodeInvalidOrAlreadyUsed,
  errorSystem,
  errorSystemGeneric;

  KratosErrors forId(int id) {
    return switch (id) {
      // Login
      1010000 => KratosErrors.infoSelfServiceLoginRoot,
      1010001 => KratosErrors.infoSelfServiceLogin,
      1010002 => KratosErrors.infoSelfServiceLoginWith,
      1010003 => KratosErrors.infoSelfServiceLoginReAuth,
      1010004 => KratosErrors.infoSelfServiceLoginMFA,
      1010005 => KratosErrors.infoSelfServiceLoginVerify,
      1010006 => KratosErrors.infoSelfServiceLoginTOTPLabel,
      1010007 => KratosErrors.infoLoginLookupLabel,
      1010008 => KratosErrors.infoSelfServiceLoginWebAuthn,
      1010009 => KratosErrors.infoLoginTOTP,
      1010010 => KratosErrors.infoLoginLookup,
      1010011 => KratosErrors.infoSelfServiceLoginContinueWebAuthn,
      1010012 => KratosErrors.infoSelfServiceLoginWebAuthnPasswordless,
      1010013 => KratosErrors.infoSelfServiceLoginContinue,

      // Logout
      1020000 => KratosErrors.infoSelfServiceLogout,

      // MFA
      1030000 => KratosErrors.infoSelfServiceMFA,

      // Registration
      1040000 => KratosErrors.infoSelfServiceRegistrationRoot,
      1040001 => KratosErrors.infoSelfServiceRegistration,
      1040002 => KratosErrors.infoSelfServiceRegistrationWith,
      1040003 => KratosErrors.infoSelfServiceRegistrationContinue,
      1040004 => KratosErrors.infoSelfServiceRegistrationRegisterWebAuthn,

      // Settings
      1050000 => KratosErrors.infoSelfServiceSettings,
      1050001 => KratosErrors.infoSelfServiceSettingsUpdateSuccess,
      1050002 => KratosErrors.infoSelfServiceSettingsUpdateLinkOidc,
      1050003 => KratosErrors.infoSelfServiceSettingsUpdateUnlinkOidc,
      1050004 => KratosErrors.infoSelfServiceSettingsUpdateUnlinkTOTP,
      1050005 => KratosErrors.infoSelfServiceSettingsTOTPQRCode,
      1050006 => KratosErrors.infoSelfServiceSettingsTOTPSecret,
      1050007 => KratosErrors.infoSelfServiceSettingsRevealLookup,
      1050008 => KratosErrors.infoSelfServiceSettingsRegenerateLookup,
      1050009 => KratosErrors.infoSelfServiceSettingsLookupSecret,
      1050010 => KratosErrors.infoSelfServiceSettingsLookupSecretLabel,
      1050011 => KratosErrors.infoSelfServiceSettingsLookupConfirm,
      1050012 => KratosErrors.infoSelfServiceSettingsRegisterWebAuthn,
      1050013 =>
        KratosErrors.infoSelfServiceSettingsRegisterWebAuthnDisplayName,
      1050014 => KratosErrors.infoSelfServiceSettingsLookupSecretUsed,
      1050015 => KratosErrors.infoSelfServiceSettingsLookupSecretList,
      1050016 => KratosErrors.infoSelfServiceSettingsDisableLookup,
      1050017 => KratosErrors.infoSelfServiceSettingsTOTPSecretLabel,
      1050018 => KratosErrors.infoSelfServiceSettingsRemoveWebAuthn,

      // Recovery
      1060000 => KratosErrors.infoSelfServiceRecovery,
      1060001 => KratosErrors.infoSelfServiceRecoverySuccessful,
      1060002 => KratosErrors.infoSelfServiceRecoveryEmailSent,
      1060003 => KratosErrors.infoSelfServiceRecoveryEmailWithCodeSent,

      // Node Label
      1070000 => KratosErrors.infoNodeLabel,
      1070001 => KratosErrors.infoNodeLabelInputPassword,
      1070002 => KratosErrors.infoNodeLabelGenerated,
      1070003 => KratosErrors.infoNodeLabelSave,
      1070004 => KratosErrors.infoNodeLabelID,
      1070005 => KratosErrors.infoNodeLabelSubmit,
      1070006 => KratosErrors.infoNodeLabelVerifyOTP,
      1070007 => KratosErrors.infoNodeLabelEmail,
      1070008 => KratosErrors.infoNodeLabelResendOTP,
      1070009 => KratosErrors.infoNodeLabelContinue,
      1070010 => KratosErrors.infoNodeLabelRecoveryCode,
      1070011 => KratosErrors.infoNodeLabelVerificationCode,

      // Verification
      1080000 => KratosErrors.infoSelfServiceVerification,
      1080001 => KratosErrors.infoSelfServiceVerificationEmailSent,
      1080002 => KratosErrors.infoSelfServiceVerificationSuccessful,
      1080003 => KratosErrors.infoSelfServiceVerificationEmailWithCodeSent,

      // Validation Error
      4000000 => KratosErrors.errorValidation,
      4000001 => KratosErrors.errorValidationGeneric,
      4000002 => KratosErrors.errorValidationRequired,
      4000003 => KratosErrors.errorValidationMinLength,
      4000004 => KratosErrors.errorValidationInvalidFormat,
      4000005 => KratosErrors.errorValidationPasswordPolicyViolation,
      4000006 => KratosErrors.errorValidationInvalidCredentials,
      4000007 => KratosErrors.errorValidationDuplicateCredentials,
      4000008 => KratosErrors.errorValidationTOTPVerifierWrong,
      4000009 => KratosErrors.errorValidationIdentifierMissing,
      4000010 => KratosErrors.errorValidationAddressNotVerified,
      4000011 => KratosErrors.errorValidationNoTOTPDevice,
      4000012 => KratosErrors.errorValidationLookupAlreadyUsed,
      4000013 => KratosErrors.errorValidationNoWebAuthnDevice,
      4000014 => KratosErrors.errorValidationNoLookup,
      4000015 => KratosErrors.errorValidationSuchNoWebAuthnUser,
      4000016 => KratosErrors.errorValidationLookupInvalid,
      4000017 => KratosErrors.errorValidationMaxLength,
      4000018 => KratosErrors.errorValidationMinimum,
      4000019 => KratosErrors.errorValidationExclusiveMinimum,
      4000020 => KratosErrors.errorValidationMaximum,
      4000021 => KratosErrors.errorValidationExclusiveMaximum,
      4000022 => KratosErrors.errorValidationMultipleOf,
      4000023 => KratosErrors.errorValidationMaxItems,
      4000024 => KratosErrors.errorValidationMinItems,
      4000025 => KratosErrors.errorValidationUniqueItems,
      4000026 => KratosErrors.errorValidationWrongType,
      4000027 => KratosErrors.errorValidationDuplicateCredentialsOnOIDCLink,

      // Login Validation Error
      4010000 => KratosErrors.errorValidationLogin,
      4010001 => KratosErrors.errorValidationLoginFlowExpired,
      4010002 => KratosErrors.errorValidationLoginNoStrategyFound,
      4010003 => KratosErrors.errorValidationRegistrationNoStrategyFound,
      4010004 => KratosErrors.errorValidationSettingsNoStrategyFound,
      4010005 => KratosErrors.errorValidationRecoveryNoStrategyFound,
      4010006 => KratosErrors.errorValidationVerificationNoStrategyFound,

      // Registration Validation Error
      4040000 => KratosErrors.errorValidationRegistration,
      4040001 => KratosErrors.errorValidationRegistrationFlowExpired,

      // Settings Validation Error
      4050000 => KratosErrors.errorValidationSettings,
      4050001 => KratosErrors.errorValidationSettingsFlowExpired,

      // Recovery Validation Error
      4060000 => KratosErrors.errorValidationRecovery,
      4060001 => KratosErrors.errorValidationRecoveryRetrySuccess,
      4060002 => KratosErrors.errorValidationRecoveryStateFailure,
      4060003 => KratosErrors.errorValidationRecoveryMissingRecoveryToken,
      4060004 => KratosErrors.errorValidationRecoveryTokenInvalidOrAlreadyUsed,
      4060005 => KratosErrors.errorValidationRecoveryFlowExpired,
      4060006 => KratosErrors.errorValidationRecoveryCodeInvalidOrAlreadyUsed,

      // Verification Validation Error
      4070000 => KratosErrors.errorValidationVerification,
      4070001 =>
        KratosErrors.errorValidationVerificationTokenInvalidOrAlreadyUsed,
      4070002 => KratosErrors.errorValidationVerificationRetrySuccess,
      4070003 => KratosErrors.errorValidationVerificationStateFailure,
      4070004 =>
        KratosErrors.errorValidationVerificationMissingVerificationToken,
      4070005 => KratosErrors.errorValidationVerificationFlowExpired,
      4070006 =>
        KratosErrors.errorValidationVerificationCodeInvalidOrAlreadyUsed,

      // System Error
      5000000 => KratosErrors.errorSystem,
      5000001 => KratosErrors.errorSystemGeneric,
      _ => KratosErrors.errorSystemGeneric
    };
  }
}
